### ISSUE TITLE
Installationsskript

### ISSUE THREAD

**Issue by kpleiss** [rolfstarke/wm66_brew#26]
Wir sollten darüber nachdenken einen Installationsskript zu erstellen. Das Ziel muss heißen mehr Zeit zum trinken, weniger zum Arbeiten

**Comment by rolfstarke** [comment]
oder ein komplettes Pi image

**Comment by kpleiss** [comment]
Das ganz dringed!

**Comment by kpleiss** [comment]
siehe auch #14

**Comment by kpleiss** [comment]
Ich glaube das ist in Anbetracht von #14 Quatsch
