### ISSUE TITLE
Thermsensor Absturzmiesere

### ISSUE THREAD

**Issue by rolfstarke** [rolfstarke/wm66_brew#27]
Sensorabfrage mit try kapseln und Code störfester machen

**Comment by kpleiss** [comment]
ok, ich glaube er wird nicht zu oft abgefragt. wir müssen für die zwei fehlerfälle (88° und wenn der telegram bot abfragt) die exceptions wissen, diese auffangen und dann nach z.b. 1 sec wieder abfragen

**Comment by kpleiss** [comment]
Aktueller Wissensstand: 80°C ist ein Fehlercode für den Sensor. Also einfach mit try kapseln und gut ist...

**Comment by kpleiss** [comment]
endlich erledigt, mit einem ehrlichen schwipps
