### ISSUE TITLE
Unterlegscheibe erneuern

### ISSUE THREAD

**Issue by kpleiss** [rolfstarke/wm66_brew#3]
Die Unterlegscheibe am ehemaligen Abfluss muss Säure/Laugenfest sein

**Comment by kpleiss** [comment]
Unterlegscheiben sind besorgt

**Comment by rolfstarke** [comment]
Scheibe umgedreht. korrosionsbeständige Scheibe kaufen

**Comment by kpleiss** [comment]
Ist erledigt, oder? @rolfstarke
