### ISSUE TITLE
Repos aktualisieren

### ISSUE THREAD

**Issue by rolfstarke** [rolfstarke/wm66_brew#33]
https://forum.iobroker.net/topic/62040/linux-debian-grafana-repo-muss-aktualisiert-werden

**Comment by kpleiss** [comment]
das influxdb repo muss vermutlich auch aktualisiert werden...

**Comment by kpleiss** [comment]
https://www.influxdata.com/blog/linux-package-signing-key-rotation/

**Comment by kpleiss** [comment]
Erledigt. Nacharbeiten #52
