### ISSUE TITLE
Code modularisieren

### ISSUE THREAD

**Issue by kpleiss** [rolfstarke/wm66_brew#36]

**Comment by kpleiss** [comment]
Also ich habe im Options Branch die temperatur und die influxdb in extra .py geschrieben. Das ursprüngliche brew skript ist in der wart.py und muss aufgeräumt werden

**Comment by kpleiss** [comment]
der plan ist jetzt: gpios und variablen in eine options datei schreiben, sodass die zentral abgelegt sind. wir nutzen für die kommandolinien optionen getopt (hat chatgpt entschieden). Es gibt eine zentrale brew.py. Diese startet prozess .pys. brew, wart, cool,... Außerdem gibt es einzelne aktionen, die oft aufgerufen werden und in eigenen .pys sind. themperatur abrufen, influxdb,...

**Comment by rolfstarke** [comment]
- [ ] Options branch debuggen
