### ISSUE TITLE
Motorrücklauf ermöglichen

### ISSUE THREAD

**Issue by rolfstarke** [rolfstarke/wm66_brew#41]

**Comment by kpleiss** [comment]
Prüfen, ob es sinnvoll ist beim Läutern das Wellrad durch schnellen Vor- und Rücklauf zu rütteln und dadurch den Treber aufzubrechen, wenn der Durchfluss schlecht ist.
Dafür bräuchte es ein Relais und einen Taster um es auszulösen.
Davor Tests, ob das überhaupt sinnig ist!

**Comment by kpleiss** [comment]
Eventuell braucht man zunächst auch gar keinen Rücklauf, sondern es reicht, wenn das Wellrad einfach nur ruckartig anfährt und stoppt
